image: node:latest

pages:
  tags:
    - docker
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm start
  artifacts:
    paths:
      - public
  only:
    - main