image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build-pages:
  stage: build
  script:
    - rm -rf build
    - CI=false npm install
    - CI=false npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master

pages:
  stage: deploy
  script:
    -ls #just something
  artifacts:
    paths:
      - public
  only:
    - master
    